# Generated by Django 4.2.1 on 2023-07-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProfessional',
            fields=[
                ('ap_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ap_name', models.CharField(max_length=100)),
                ('ap_mobile', models.CharField(max_length=100)),
                ('ap_email', models.CharField(max_length=100)),
                ('ap_password', models.CharField(max_length=100)),
                ('ap_role', models.CharField(max_length=100)),
                ('ap_status', models.IntegerField(default=0)),
                ('ap_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AddServiceProfessional',
            fields=[
                ('ab_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ab_name', models.CharField(max_length=100)),
                ('ab_email', models.CharField(default='', max_length=100)),
                ('ab_mobile', models.CharField(default='', max_length=100)),
                ('ab_service_name', models.CharField(default='', max_length=100)),
                ('ab_price', models.CharField(max_length=100)),
                ('ab_details', models.CharField(max_length=100)),
                ('ab_image', models.ImageField(upload_to='app/static/media/professional/')),
                ('ab_status', models.IntegerField(default=0)),
                ('ab_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdminMaster',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ad_name', models.CharField(max_length=100)),
                ('ad_mobile', models.CharField(max_length=100)),
                ('ad_email', models.CharField(max_length=100)),
                ('ad_password', models.CharField(max_length=100)),
                ('ad_role', models.CharField(max_length=100)),
                ('ad_status', models.IntegerField(default=0)),
                ('ad_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('or_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('or_name', models.CharField(max_length=100)),
                ('or_service_name', models.CharField(max_length=100)),
                ('or_total_amount', models.CharField(max_length=100)),
                ('or_address', models.CharField(max_length=100)),
                ('or_ordered_by', models.CharField(max_length=100)),
                ('or_transaction_id', models.CharField(max_length=100)),
                ('or_status', models.CharField(default=0, max_length=100)),
                ('or_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('rg_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rg_name', models.CharField(max_length=100)),
                ('rg_mobile', models.CharField(max_length=100)),
                ('rg_email', models.CharField(max_length=100)),
                ('rg_password', models.CharField(max_length=100)),
                ('rg_address', models.CharField(default='', max_length=100)),
                ('rg_status', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('sv_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sv_name', models.CharField(max_length=100)),
                ('sv_status', models.IntegerField(default=0)),
                ('sv_created_by', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
