# Generated by Django 4.2.3 on 2023-07-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_or_email_order_or_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='or_location',
            field=models.TextField(default=''),
        ),
    ]
