# Generated by Django 4.2.3 on 2023-07-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_or_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='or_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='or_time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
