# Generated by Django 4.2.3 on 2023-07-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_or_date_order_or_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='or_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
