# Generated by Django 4.2.3 on 2023-08-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_or_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fd_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fd_name', models.CharField(max_length=100)),
                ('fd_mobile', models.CharField(max_length=100)),
                ('rg_email', models.CharField(max_length=100)),
                ('fd_feedback', models.CharField(max_length=100)),
                ('fd_category', models.CharField(max_length=100)),
                ('fd_status', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AddProfessional',
        ),
        migrations.DeleteModel(
            name='AddServiceProfessional',
        ),
        migrations.DeleteModel(
            name='AdminMaster',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.RemoveField(
            model_name='register',
            name='rg_address',
        ),
    ]
