# Generated by Django 4.2.3 on 2023-08-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_register_rg_name_register_rg_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='fd_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fd_category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fd_feedback',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fd_mobile',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fd_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rg_email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
