# Generated by Django 4.2.3 on 2023-08-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_feedback_fd_type_alter_feedback_fd_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMaster',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ad_name', models.CharField(max_length=100)),
                ('ad_mobile', models.CharField(max_length=100)),
                ('ad_email', models.CharField(max_length=100)),
                ('ad_password', models.CharField(max_length=100)),
                ('ad_role', models.CharField(max_length=100)),
                ('ad_status', models.CharField(max_length=100)),
                ('ad_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
