# Generated by Django 4.2.2 on 2024-02-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_adminmaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='rg_email',
            new_name='fd_email',
        ),
    ]
