# Generated by Django 4.2.2 on 2024-02-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_rg_email_feedback_fd_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='fd_created_at',
            field=models.CharField(default='', max_length=100),
        ),
    ]
