# Generated by Django 4.2.3 on 2024-03-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_feedback_fd_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='fd_feedback',
            field=models.TextField(default=''),
        ),
    ]
