# Generated by Django 5.0.3 on 2024-03-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_feedback_fd_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('ct_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ct_category', models.CharField(default='', max_length=100)),
                ('ct_status', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('ht_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ht_name', models.CharField(default='', max_length=100)),
                ('ht_area', models.CharField(default='', max_length=100)),
                ('ht_city', models.CharField(default='', max_length=100)),
                ('ht_recipe', models.CharField(default='', max_length=100)),
                ('ht_status', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('rc_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rc_category', models.CharField(default='', max_length=100)),
                ('rc_recipe', models.CharField(default='', max_length=100)),
                ('rc_steps', models.CharField(default='', max_length=100)),
                ('rc_video', models.CharField(default='', max_length=100)),
                ('rc_status', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
