# Generated by Django 5.0.3 on 2024-03-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_category_hotels_recipe_delete_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmaster',
            name='ad_status',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
